"""create stories table

Revision ID: b6cf31523cb9
Revises: 
Create Date: 2026-01-10 21:44:29.786970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cf31523cb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hn_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_ai_related', sa.Boolean(), nullable=False),
    sa.Column('hn_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_score', 'stories', ['is_ai_related', 'score'], unique=False)
    op.create_index('idx_posted_at', 'stories', ['posted_at'], unique=False)
    op.create_index(op.f('ix_stories_hn_id'), 'stories', ['hn_id'], unique=True)
    op.create_index(op.f('ix_stories_is_ai_related'), 'stories', ['is_ai_related'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_is_ai_related'), table_name='stories')
    op.drop_index(op.f('ix_stories_hn_id'), table_name='stories')
    op.drop_index('idx_posted_at', table_name='stories')
    op.drop_index('idx_ai_score', table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
